"""Changed users table column name: username

Revision ID: 303f54ae3e41
Revises: 057b6842a5e7
Create Date: 2026-07-07 14:41:17.053272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303f54ae3e41'
down_revision: Union[str, Sequence[str], None] = '057b6842a5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=225), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
