"""added title_generated bool to conversation

Revision ID: 68612d717c9d
Revises: 9df622bd1524
Create Date: 2026-07-16 21:29:02.837497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68612d717c9d'
down_revision: Union[str, Sequence[str], None] = '9df622bd1524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title_generated')
    # ### end Alembic commands ###
