"""change vector dimensions

Revision ID: 829058d976c6
Revises: 36aa86e5b0c3
Create Date: 2026-07-11 16:41:19.419207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '829058d976c6'
down_revision: Union[str, Sequence[str], None] = '36aa86e5b0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
